### ISSUE TITLE
JITB-17: Fix "missing Chrome" BUG

### ISSUE THREAD

**Issue by hark130** [hark130/jack-in-the-box#22]
I was running JITB in Windows.  No Chrome installed.  It hung.  Couldn't kill it.  No error message(?).

```
C:\Users\hark1\Documents\Personal\Programming\jack-in-the-box>python -m jitb --room klaf --user jitb --debug
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hark1\Documents\Personal\Programming\jack-in-the-box\jitb\__main__.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\hark1\Documents\Personal\Programming\jack-in-the-box\jitb\jitb_main.py", line 29, in main
    play_the_game(room_code=room_code, username=username, ai_obj=client)
  File "C:\Users\hark1\Documents\Personal\Programming\jack-in-the-box\jitb\jitb_website.py", line 106, in play_the_game
    web_driver = join_room(room_code=room_code, username=username)  # Webdriver for Jackbox Games
  File "C:\Users\hark1\Documents\Personal\Programming\jack-in-the-box\jitb\jitb_website.py", line 81, in join_room
    driver = webdriver.Chrome()  # Webdriver object
  File "C:\Users\hark1\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\hark1\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\chromium\webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\hark1\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\hark1\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\hark1\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hark1\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: DevToolsActivePort file doesn't exist
Stacktrace:
        GetHandleVerifier [0x00007FF758AD7012+3522402]
        (No symbol) [0x00007FF7586F8352]
        (No symbol) [0x00007FF7585A5ABB]
        (No symbol) [0x00007FF7585DB0FA]
        (No symbol) [0x00007FF7585D4E3E]
        (No symbol) [0x00007FF7585D2188]
        (No symbol) [0x00007FF758619469]
        (No symbol) [0x00007FF75860EE03]
        (No symbol) [0x00007FF7585DF4D4]
        (No symbol) [0x00007FF7585E05F1]
        GetHandleVerifier [0x00007FF758B09B9D+3730157]
        GetHandleVerifier [0x00007FF758B5F02D+4079485]
        GetHandleVerifier [0x00007FF758B575D3+4048163]
        GetHandleVerifier [0x00007FF75882A649+718233]
        (No symbol) [0x00007FF758704A3F]
        (No symbol) [0x00007FF7586FFA94]
        (No symbol) [0x00007FF7586FFBC2]
        (No symbol) [0x00007FF7586EF2E4]
        BaseThreadInitThunk [0x00007FFF2D487344+20]
        RtlUserThreadStart [0x00007FFF2E2C26B1+33]
```

**Comment by hark130** [comment]
Instead of programmatically fixing/validating a Chrome installation, I added it as a requirement to the project documentation.
