### ISSUE TITLE
JITB-27: Does the debug logger have a BUG?

### ISSUE THREAD

**Issue by hark130** [hark130/jack-in-the-box#36]
Running the unit tests resulted in some unexpected failures (on `JITB-13`).  Is this my problem?  (Top of my head... am I not closing the debug log file?!)  Is this the OS's problem?  (I've got the `--debug` flag turned on for all unit tests, even though I haven't used any of them in a while)  If it's the OS's problem, I still need to work around it.  Maybe I default all of these test clases to `debug = False` but turn on unit test debugging, as needed.

SIDE NOTE: I've had some success in the past passing a command-line argument to the `python -m test` command... Maybe that's the way to turn on unit test debugging.

```
======================================================================
ERROR: test_s07_round_3_prompt_1_v2 (unit_test.test_selenium.test_get_web_element_text.SpecialTestJitbSeleniumGetWebElementText)
KEY TEXT: Quiplash 2 Round 3 Last Lash prompt page v2; value state-answer-question.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/test/unit_test/test_jackbox_games.py", line 56, in setUp
    Logger.initialize(debugging=True)  # Enable DEBUG logging while testing
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/jitb/jitb_logger.py", line 88, in initialize
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
OSError: [Errno 24] Too many open files: '/tmp/jitb_20240305_124256.log'

======================================================================
ERROR: test_s08_round_3_prompt_1_v2_take_2 (unit_test.test_selenium.test_get_web_element_text.SpecialTestJitbSeleniumGetWebElementText)
KEY TEXT: Quiplash 2 Round 3 Last Lash prompt page v2; value question-text-alt.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/test/unit_test/test_jackbox_games.py", line 56, in setUp
    Logger.initialize(debugging=True)  # Enable DEBUG logging while testing
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/jitb/jitb_logger.py", line 88, in initialize
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
OSError: [Errno 24] Too many open files: '/tmp/jitb_20240305_124256.log'

======================================================================
ERROR: test_s09_round_3_vote_1_v1 (unit_test.test_selenium.test_get_web_element_text.SpecialTestJitbSeleniumGetWebElementText)
KEY TEXT: Quiplash 2 Round 3 Last Lash vote page v1; value state-vote.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/test/unit_test/test_jackbox_games.py", line 56, in setUp
    Logger.initialize(debugging=True)  # Enable DEBUG logging while testing
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/jitb/jitb_logger.py", line 88, in initialize
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
OSError: [Errno 24] Too many open files: '/tmp/jitb_20240305_124256.log'

======================================================================
ERROR: test_s11_round_3_vote_1_v2 (unit_test.test_selenium.test_get_web_element_text.SpecialTestJitbSeleniumGetWebElementText)
KEY TEXT: Quiplash 2 Round 3 Last Lash vote page v2; value state-vote.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/test/unit_test/test_jackbox_games.py", line 56, in setUp
    Logger.initialize(debugging=True)  # Enable DEBUG logging while testing
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/jitb/jitb_logger.py", line 88, in initialize
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
OSError: [Errno 24] Too many open files: '/tmp/jitb_20240305_124256.log'

======================================================================
ERROR: test_s13_non_jackbox_game_page (unit_test.test_selenium.test_get_web_element_text.SpecialTestJitbSeleniumGetWebElementText)
Non-Jackbox Games website.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/test/unit_test/test_jackbox_games.py", line 56, in setUp
    Logger.initialize(debugging=True)  # Enable DEBUG logging while testing
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/jitb/jitb_logger.py", line 88, in initialize
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
OSError: [Errno 24] Too many open files: '/tmp/jitb_20240305_124256.log'
```

**Comment by hark130** [comment]
Glancing at the debug log again, it's possible the test cases are running so fast they're trying to use the same filename.
Maybe some additional filename distinction is necessary.  Something like...

```
File exists?
Append a letter to the proposed filename.
Look again (AKA recursively loop)
```

**Comment by hark130** [comment]
Fixed
